update onceover
puppetlabs/puppet-dev-tools pull request #117
Opened 2022-06-08 08:00 UTC by tuxmea

2022-06-29 21:29 UTC, eputnam requested changes
Thanks for this @tuxmea! If you have time, it'd also be great to add any notes about what you're looking forward to in having this new version of onceover in your commit, i.e. was there something specific that motivated this change?

2022-06-29 21:29 UTC, eputnam commented on Dockerfile
> +ARG GH_USER=tuxmea
```suggestion
ARG GH_USER=puppetlabs
```

2022-06-29 21:29 UTC, eputnam commented on Dockerfile
> +<<<<<<< HEAD
looks like maybe an artifact from some conflict resolution, unfortunately not valid Dockerfile syntax :)

2022-07-25 12:30 UTC, tuxmea commented
@eputnam sorry for the late reply. I did the changes and updated the mr description.

2022-07-27 23:03 UTC, eputnam commented
was the `cmake` install on here before? what is requiring that?

2022-08-24 10:15 UTC, tuxmea commented
@eputnam sorry for the late reply. I had to dig for myself:

onceover-octocatalog-diff depends on octocatalog-diff which depends on rugged, which needs cmake.

2022-08-25 17:24 UTC, eputnam approved these changes

2022-08-25 17:27 UTC, merged